<?php
    echo
    "
    <option value='select'> Select Equipment</option>
    <option value='pb' disabled>Adventuring Gear</option>
    <option value='Abacus'>Abacus</option>
    <option value='Acid (vial)'>Acid (vial)</option>
    <option value='Airship'>Airship</option>
    <option value='Alchemist's Fire (flask)'>Alchemist's Fire (flask)</option>
    <option value='Alms Box'>Alms Box</option>
    <option value='Antitoxin'>Antitoxin</option>
    <option value='Backpack'>Backpack</option>
    <option value='Ball Bearings (bag of 1,000)'>Ball Bearings (bag of 1,000)</option>
    <option value='Barding'>Barding</option>
    <option value='Barrel'>Barrel</option>
    <option value='Basket'>Basket</option>
    <option value='Bedroll'>Bedroll</option>
    <option value='Bell'>Bell</option>
    <option value='Bit and Bridle'>Bit and Bridle</option>
    <option value='Blanket'>Blanket</option>
    <option value='Blasting Powder'>Blasting Powder</option>
    <option value='Block and Tackle'>Block and Tackle</option>
    <option value='Block of Incense'>Block of Incense</option>
    <option value='Bomb'>Bomb</option>
    <option value='Book'>Book</option>
    <option value='Boots'>Boots</option>
    <option value='Bottle, Glass'>Bottle, Glass</option>
    <option value='Caltrops (Bag of 20)'>Caltrops (Bag of 20)</option>
    <option value='Candle'>Candle</option>
    <option value='Canoe'>Canoe</option>
    <option value='Case, Crossbow Bolt'>Case, Crossbow Bolt</option>
    <option value='Case, Map or Scroll'>Case, Map or Scroll</option>
    <option value='Censer'>Censer</option>
    <option value='Chain (10 feet)'>Chain (10 feet)</option>
    <option value='Chalk (1 piece)'>Chalk (1 piece)</option>
    <option value='Chest'>Chest</option>
    <option value='Climber's Kit'>Climber's Kit</option>
    <option value='Clothes, Common'>Clothes, Common</option>
    <option value='Clothes, Costume'>Clothes, Costume</option>
    <option value='Clothes, Fine'>Clothes, Fine</option>
    <option value='Clothes, Traveler's'>Clothes, Traveler's</option>
    <option value='Clothing, cold weather'>Clothing, cold weather</option>
    <option value='Component Pouch'>Component Pouch</option>
    <option value='Crampons'>Crampons</option>
    <option value=Dynamite (Stick)''>Dynamite (Stick)</option>
    <option value='Eberron Dragonshard'>Eberron Dragonshard</option>
    <option value='Crowbar'>Crowbar</option>
    <option value='Explosive Seed'>Explosive Seed</option>
    <option value='Feed (per day)'>Feed (per day)</option>
    <option value='Fishing Tackle'>Fishing Tackle</option>
    <option value='Flask or Tankard'>Flask or Tankard</option>
    <option value='Grappling Hook'>Grappling Hook</option>
    <option value='Grenade Launcher'>Grenade Launcher</option>
    <option value='Grenade, Fragmentation'>Grenade, Fragmentation</option>
    <option value='Grenade, Smoke'>Grenade, Smoke</option>
    <option value='Grenade, Keg'>Grenade, Keg</option>
    <option value='Grenade, Powder Horn'>Grenade, Powder Horn</option>
    <option value='Hammer'>Hammer</option>
    <option value='Hammer, Sledge'>Hammer, Sledge</option>
    <option value='Healer's Kit'>Healer's Kit</option>
    <option value='Helm'>Helm</option>
    <option value='Holy Water (flask)'>Holy Water (flask)</option>
    <option value='Hourglass'>Hourglass</option>
    <option value='Hunting Trap'>Hunting Trap</option>
    <option value='Ink (1 ounce bottle)'>Ink (1 ounce bottle)</option>
    <option value='Ink Pen'>Ink Pen</option>
    <option value='Insect Repellent-Incense'>Insect Repellent-Incense</option>
    <option value='Insect Repellent-Salve'>Insect Repellent-Salve</option>
    <option value='Jug or Pitcher'>Jug or Pitcher</option>
    <option value='Khyber Dragonshard'>Khyber Dragonshard</option>
    <option value='Ladder (10 foot)'>Ladder (10 foot)</option>
    <option value='Lamp'>Lamp</option>
    <option value='Lantern, Bullseye'>Lantern, Bullseye</option>
    <option value='Lantern, Hooded'>Lantern, Hooded</option>
    <option value='Little Bag of Sand'>Little Bag of Sand</option>
    <option value='Lock'>Lock</option>
    <option value='Magnifying Glass'>Magnifying Glass</option>
    <option value='Manacles'>Manacles</option>
    <option value='Mess Kit'>Mess Kit</option>
    <option value='Mirror, Steel'>Mirror, Steel</option>
    <option value='Oil (flask)'>Oil (flask)</option>
    <option value='Paper (one sheet)'>Paper (one sheet)</option>
    <option value='Parchment (one sheet)'>Parchment (one sheet)</option>
    <option value='Perfume (vial)'>Perfume (vial)</option>
    <option value='Pick, Miner's'>Pick, Miner's</option>
    <option value='Piton'>Piton</option>
    <option value='Pole (10-foot)'>Pole (10-foot)</option>
    <option value='Pot, Iron'>Pot, Iron</option>
    <option value='Pouch'>Pouch</option>
    <option value='Pride Silk'>Pride Silk</option>
    <option value='Quiver'>Quiver</option>
    <option value='Rain Catcher'>Rain Catcher</option>
    <option value='Ram, Portable'>Ram, Portable</option>
    <option value='Rations (1 day)'>Rations (1 day)</option>
    <option value='Robes'>Robes</option
    <option value='Rope, Hempen (50 feet)'>Rope, Hempen (50 feet)</option>
    <option value='Rope, Silk (50 feet)'>Rope, Silk (50 feet)</option>
    <option value='Sack'>Sack</option>
    <option value='Saddle, Exotic'>Saddle, Exotic</option>
    <option value='Saddle, Pack'>Saddle, Pack</option>
    <option value='Saddle, Riding'>Saddle, Riding</option>
    <option value='Saddlebags'>Saddlebags</option>
    <option value='Scale, Merchant's'>Scale, Merchant's</option>
    <option value=Sealing Wax''>Sealing Wax</option>
    <option value='Shovel'>Shovel</option>
    <option value='Siberys Dragonshard'>Siberys Dragonshard</option>
    <option value='Signal Whistle'>Signal Whistle</option>
    <option value='Signet Ring'>Signet Ring</option>
    <option value='Small Knife'>Small Knife</option>
    <option value='Snowshoes'>Snowshoes</option>
    <option value='Soap'>Soap</option>
    <option value='Spellbook'>Spellbook</option>
    <option value='Spikes, Iron (10)'>Spikes, Iron (10)</option>
    <option value='Spyglass'>Spyglass</option>
    <option value='Stake (Wooden)'>Stake (Wooden)</option>
    <option value='String'>String</option>
    <option value='Tangler Grenade'>Tangler Grenade</option>
    <option value='Tej'>Tej</option>
    <option value='Tent, Two-Person'>Tent, Two-Person</option>
    <option value='Tinderbox'>Tinderbox</option>
    <option value='Torch'>Torch</option>
    <option value='Vestments'>Vestments</option>
    <option value='Vial'>Vial</option>
    <option value='Waterskin'>Waterskin</option>
    <option value='Whetstone'>Whetstone</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Ammunition</option>
    <option value='Arrows'>Arrows</option>
    <option value='Bad News Bullets'>Bad News Bullets</option>
    <option value='Blowgun Needles'>Blowgun Needles</option>
    <option value='Blunderbuss Bullets'>Blunderbuss Bullets</option>
    <option value='Bucket'>Bucket</option>
    <option value='Bullets, Modern'>Bullets, Modern</option>
    <option value='Bullets, Renaissance'>Bullets, Renaissance</option>
    <option value='Crossbow Bolts'>Crossbow Bolts</option>
    <option value='Energy Cell'>Energy Cell</option>
    <option value='Hand Mortar Ammunition'>Hand Mortar Ammunition</option>
    <option value='Musket (Exandria) Bullets'>Musket (Exandria) Bullets</option>
    <option value='Palm Pistol Bullets'>Palm Pistol Bullets</option>
    <option value='Pistol (Exandria) Bullets'>Pistol (Exandria) Bullets</option>
    <option value='Sling Bullets'>Sling Bullets</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Arcane Focus</option>
    <option value='Arcane Focus'>Arcane Focus</option>
    <option value='Crystal'>Crystal</option>
    <option value='Orb'>Orb</option>
    <option value=Rod''>Rod</option>
    <option value='Staff'>Staff</option>
    <option value='Wand'>Wand</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Druidic Focus</option>
    <option value='Druidic Focus'>Druidic Focus</option>
    <option value='Sprig of Mistletoe'>Sprig of Mistletoe</option>
    <option value='Totem'>Totem</option>
    <option value='Wooden Staff'>Wooden Staff</option>
    <option value='Yew Wand'>Yew Wand</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Equipment Pack</option>
    <option value='Burglar's Pack'>Burglar's Pack</option>
    <option value='Diplomat's Pack'>Diplomat's Pack</option>
    <option value='Dungeoneer's Pack'>Dungeoneer's Pack</option>
    <option value='Entertainer's Pack'>Entertainer's Pack</option>
    <option value='Explorer's Pack'>Explorer's Pack</option>
    <option value='Monster Hunter's Pack'>Monster Hunter's Pack</option>
    <option value='Priest's Pack'>Priest's Pack</option>
    <option value='Scholar's Pack'>Scholar's Pack</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Firearms Ranged Weapon</option>
    <option value='Antimatter Rifle'>Antimatter Rifle</option>
    <option value='Bad News(Exandria)'>Bad News(Exandria)</option>
    <option value='Blunderbuss (Exandria)'>Blunderbuss (Exandria)</option>
    <option value='Hand Mortar (Exandria)'>Hand Mortar (Exandria)</option>
    <option value='Laser Pistol'>Laser Pistol</option>
    <option value='Laser Rifle'>Laser Rifle</option>
    <option value='Musket'>Musket</option>
    <option value='Musket (Exandria)'>Musket (Exandria)</option>
    <option value='Palm Pistol (Exandria)'>Palm Pistol (Exandria)</option>
    <option value='Pistol'>Pistol</option>
    <option value='Pistol (Exandria)'>Pistol (Exandria)</option>
    <option value='Pistol, Automatic'>Pistol, Automatic</option>
    <option value='Revolver'>Revolver</option>
    <option value='Rifle, Automatic'>Rifle, Automatic</option>
    <option value='Rifle, Hunting'>Rifle, Hunting</option>
    <option value='Shotgun'>Shotgun</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Gemstone</option>
    <option value='Alexandrite'>Alexandrite</option>
    <option value='Amber'>Amber</option>
    <option value='Amethyst'>Amethyst</option>
    <option value='Aquamarine'>Aquamarine</option>
    <option value='Azurite'>Azurite</option>
    <option value='Banded Agate'>Banded Agate</option>
    <option value='Black Opal'>Black Opal</option>
    <option value='Black Pearl'>Black Pearl</option>
    <option value='Black Sapphire'>Black Sapphire</option>
    <option value='Bloodstone'>Bloodstone</option>
    <option value='Blue Quartz'>Blue Quartz</option>
    <option value='Blue Sapphire'>Blue Sapphire</option>
    <option value='Blue Spinel'>Blue Spinel</option>
    <option value='Carnelian'>Carnelian</option>
    <option value='Chalcedony'>Chalcedony</option>
    <option value='Chrysoberyl'>Chrysoberyl</option>
    <option value='Chrysoprase'>Chrysoprase</option>
    <option value='Citrine'>Citrine</option>
    <option value='Coral'>Coral</option>
    <option value='Diamond'>Diamond</option>
    <option value='Emerald'>Emerald</option>
    <option value='Eye agate'>Eye agate</option>
    <option value='Fire Opal'>Fire Opal</option>
    <option value='Garnet'>Garnet</option>
    <option value='Hemalite'>Hemalite</option>
    <option value='Jacinth'>Jacinth</option>
    <option value='Jade'>Jade</option>
    <option value='Jasper'>Jasper</option>
    <option value='Jet'>Jet</option>
    <option value='Lapis Lazuli'>Lapis Lazuli</option>
    <option value='Malachite'>Malachite</option>
    <option value='Moss agate'>Moss agate</option>
    <option value='Obsidian'>Obsidian</option>
    <option value='Onyx'>Onyx</option>
    <option value='Opal'>Opal</option>
    <option value='Pearl'>Pearl</option>
    <option value='Peridot'>Peridot</option>
    <option value='Quartz'>Quartz</option>
    <option value='Rhodochrosite'>Rhodochrosite</option>
    <option value='Ruby'>Ruby</option>
    <option value='Sardonyx'>Sardonyx</option>
    <option value='Spinel'>Spinel</option>
    <option value='Star Rose Quartz'>Star Rose Quartz</option>
    <option value='Star Ruby'>Star Ruby</option>
    <option value='Star Sapphire'>Star Sapphire</option>
    <option value='Tiger Eye'>Tiger Eye</option>
    <option value='Topaz'>Topaz</option>
    <option value='Tourmaline'>Tourmaline</option>
    <option value='Turquoise'>Turquoise</option>
    <option value='Yellow sapphire'>Yellow sapphire</option>
    <option value='Zircon'>Zircon</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Heavy Armor</option>
    <option value='Chain Mail'>Chain Mail</option>
    <option value='Plate'>Plate</option>
    <option value='Ring Mail'>Ring Mail</option>
    <option value='Splint'>Splint</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Holy Symbol</option>
    <option value='Amulet'>Amulet</option>
    <option value='Emblem'>Emblem</option>
    <option value='Holy Symbol'>Holy Symbol</option>
    <option value='Reliquary'>Reliquary</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Light Armor</option>
    <option value='Leather'>Leather</option>
    <option value='Padded'>Padded</option>
    <option value='Pride Silk Outfit'>Pride Silk Outfit</option>
    <option value='Studded Leather'>Studded Leather</option>
    <option value='' disabled></option>
    
    <option value='pb' disabled>Martial Melee Weapon</option>
    <option value='Battleaxe'>Battleaxe</option>
    <option value='Double-Bladed Scimitar'>Double-Bladed Scimitar</option>
    <option value='Flail'>Flail</option>
    <option value='Glaive'>Glaive</option>
    <option value='Greataxe'>Greataxe</option>
    <option value='Greatsword'>Greatsword</option>
    <option value='Halberd'>Halberd</option>
    <option value='Lance'>Lance</option>
    <option value='Longsword'>Longsword</option>
    <option value='Maul'>Maul</option>
    <option value='Moonstone'>Moonstone</option>
    <option value='Morningstar'>Morningstar</option>
    <option value='Pike'>Pike</option>
    <option value='Rapier'>Rapier</option>
    <option value='Scimitar'>Scimitar</option>
    <option value='Shortsword'>Shortsword</option>
    <option value='Trident'>Trident</option>
    <option value='War Pick'>War Pick</option>
    <option value='Warhammer'>Warhammer</option>
    <option value='Whip'>Whip</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Martial Ranged Weapon</option>
    <option value='Blowgun'>Blowgun</option>
    <option value='Crossbow, Hand'>Crossbow, Hand</option>
    <option value='Crossbow, Heavy'>Crossbow, Heavy</option>
    <option value='Longbow'>Longbow</option>
    <option value='Net'>Net</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Medium Armor</option>
    <option value='Breastplate'>Breastplate</option>
    <option value='Chain Shirt'>Chain Shirt</option>
    <option value='Half Plate'>Half Plate</option>
    <option value='Hide'>Hide</option>
    <option value='Scale Mail'>Scale Mail</option>
    <option value='Spiked Armor'>Spiked Armor</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Mount</option>
    <option value='Axe Beak'>Axe Beak</option>
    <option value='Camel'>Camel</option>
    <option value='Donkey (or Mule)'>Donkey (or Mule)</option>
    <option value='Draft Horse'>Draft Horse</option>
    <option value='Elephant'>Elephant</option>
    <option value='Mastiff'>Mastiff</option>
    <option value='Moonbounder'>Moonbounder</option>
    <option value='Pony'>Pony</option>
    <option value='Riding Horse'>Riding Horse</option>
    <option value='Sled Dog'>Sled Dog</option>
    <option value='Warhorse'>Warhorse</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Poison</option>
    <option value='Assassin's Blood (Ingested)'>Assassin's Blood (Ingested)</option>
    <option value='Blood of the Lycanthrope (Injury)'>Blood of the Lycanthrope (Injury)</option>
    <option value='Burnt Othur Fumes (Inhaled)'>Burnt Othur Fumes (Inhaled)</option>
    <option value='Crawler Mucus (Contact)'>Crawler Mucus (Contact)</option>
    <option value='Dragon's Blood'>Dragon's Blood</option>
    <option value='Dreamlily'>Dreamlily</option>
    <option value='Drow Poison (Injury)'>Drow Poison (Injury)</option>
    <option value='Dust of the Mummy (Inhaled)'>Dust of the Mummy (Inhaled)</option>
    <option value='Essence of Ether (Inhaled)'>Essence of Ether (Inhaled)</option>
    <option value='Malice (Inhaled)'>Malice (Inhaled)</option>
    <option value='>Midnight Tears (Ingested)'>Midnight Tears (Ingested)</option>
    <option value='Oil of Taggit (Contact)'>Oil of Taggit (Contact)</option>
    <option value='Pale Tincture (Ingested)'>Pale Tincture (Ingested)</option>
    <option value='Poison, Basic (vial)'>Poison, Basic (vial)</option>
    <option value='Purple Worm Poison (Injury)'>Purple Worm Poison (Injury)</option>
    <option value='Serpent Venom (Injury)'>Serpent Venom (Injury)</option>
    <option value='Thessaltoxin (Ingested or Injury)'>Thessaltoxin (Ingested or Injury)</option>
    <option value='Torpor (Ingested)'>Torpor (Ingested)</option>
    <option value='Truth Serum (Ingested)'>Truth Serum (Ingested)</option>
    <option value=''>Wyvern Poison (Injury)</option>
    
    <option value='' disabled></option>

    <option value='pb' disabled>Potion</option>
    <option value='Black Sap'>Black Sap</option>
    <option value='Blight Ichor'>Blight Ichor</option>
    <option value='Muroosa Balm'>Muroosa Balm</option>
    <option value='Olisuba Leaf'>Olisuba Leaf</option>
    <option value='Potion of Healing'>Potion of Healing</option>
    <option value='Soothsalts'>Soothsalts</option>
    <option value='Theki Root'>Theki Root</option>
    <option value='Willowshade Oil'>Willowshade Oil</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Shield</option>
    <option value='Shield'>Shield</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Simple Melee Weapon</option>
    <option value='Club'>Club</option>
    <option value='Dagger'>Dagger</option>
    <option value='Greatclub'>Greatclub</option>
    <option value='Handaxe'>Handaxe</option>
    <option value='Javelin'>Javelin</option>
    <option value='Light Hammer'>Light Hammer</option>
    <option value='Mace'>Mace</option>
    <option value='Quarterstaff'>Quarterstaff</option>
    <option value='Sickle'>Sickle</option>
    <option value='Spear'>Spear</option>
    <option value='Yklwa'>Yklwa</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Simple Ranged Weapon</option>
    <option value='Boomerang'>Boomerang</option>
    <option value='Crossbow, Light'>Crossbow, Light</option>
    <option value='Dart'>Dart</option>
    <option value='Shortbow'>Shortbow</option>
    <option value='Sling'>Sling</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Tool</option>
    <option value='Alchemist's Supplies'>Alchemist's Supplies</option>
    <option value='Bagpipes'>Bagpipes</option>
    <option value='Birdpipes'>Birdpipes</option>
    <option value='Brewer's Supplies'>Brewer's Supplies</option>
    <option value='Calligrapher's Supplies'>Calligrapher's Supplies</option>
    <option value='Carpenter's Tools'>Carpenter's Tools</option>
    <option value='Cartographer's Tools'>Cartographer's Tools</option>
    <option value='Cobbler's Tools'>Cobbler's Tools</option>
    <option value='Cook's Utensils'>Cook's Utensils</option>
    <option value='Dice Set'>Dice Set</option>
    <option value='Disguise Kit'>Disguise Kit</option>
    <option value='Dragonchess Set'>Dragonchess Set</option>
    <option value='Drum'>Drum</option>
    <option value='Dulcimer'>Dulcimer</option>
    <option value='Flute'>Flute</option>
    <option value='Forgery Kit'>Forgery Kit</option>
    <option value='Glassblower's Tools'>Glassblower's Tools</option>
    <option value='Glaur'>Glaur</option>
    <option value='Hand Drum'>Hand Drum</option>
    <option value='Herbalism Kit'>Herbalism Kit</option>
    <option value='Horn'>Horn</option>
    <option value='Jeweler's Tools'>Jeweler's Tools</option>
    <option value='Leatherworker's Tools'>Leatherworker's Tools</option>
    <option value='Longhorn'>Longhorn</option>
    <option value='Lute'>Lute</option>
    <option value='Lyre'>Lyre</option>
    <option value='Mason's Tools'>Mason's Tools</option>
    <option value='Navigator's Tools'>Navigator's Tools</option>
    <option value='Painter's Supplies'>Painter's Supplies</option>
    <option value='Pan FLute'>Pan FLute</option>
    <option value='Playing Card Set'>Playing Card Set</option>
    <option value='Poisoner's Kit'>Poisoner's Kit</option>
    <option value='Potter's Tools'>Potter's Tools</option>
    <option value='Shawm'>Shawm</option>
    <option value='Smith's Tools'>Smith's Tools</option>
    <option value='Songhorn'>Songhorn</option>
    <option value='Tantan'>Tantan</option>
    <option value='Thelarr'>Thelarr</option>
    <option value='Thieves' Tools'>Thieves' Tools</option>
    <option value='Three-Dragon Ante Set'>Three-Dragon Ante Set</option>
    <option value='Tinker's Tools'>Tinker's Tools</option>
    <option value='Tocken'>Tocken</option>
    <option value='Viol'>Viol</option>
    <option value='Wargong'>Wargong</option>
    <option value='Weaver's Tools'>Weaver's Tools</option>
    <option value='Whistle-Stick'>Whistle-Stick</option>
    <option value='Woodcarver's Tools'>Woodcarver's Tools</option>
    <option value='Yarting'>Yarting</option>
    <option value='Zulkoon'>Zulkoon</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Vehicle (Land)</option>
    <option value='Carriage'>Carriage</option>
    <option value='Cart'>Cart</option>
    <option value='Chariot'>Chariot</option>
    <option value='Dogsled'>Dogsled</option>
    <option value='Skyship'>Skyship</option>
    <option value='Sled'>Sled</option>
    <option value='Wagon'>Wagon</option>
    <option value='' disabled></option>

    <option value='pb' disabled>Vehicle (Water)</option>
    <option value='Galley'>Galley</option>
    <option value='Keelboat'>Keelboat</option>
    <option value='Longship'>Longship</option>
    <option value='Rowboat'>Rowboat</option>
    <option value='Sailing Ship'>Sailing Ship</option>
    <option value='Warship'>Warship</option>
    <option value='' disabled></option>
    "
?>    