<?php
    echo
    "
    <option value='select'> Select Feats</option>
    <option value='Aberrant Dragonmark'>Aberrant Dragonmark</option>
    <option value='Actor'>Actor</option>
    <option value='Alert'>Alert</option>
    <option value='Artificer Initiate'>Artificer Initiate</option>
    <option value='Athlete'>Athlete</option>
    <option value='Bountiful Luck'>Bountiful Luck</option>
    <option value='Charger'>Charger</option>
    <option value='Chef'>Chef</option>
    <option value='Crossbow Expert'>Crossbow Expert</option>
    <option value='Crusher'>Crusher</option>
    <option value='Defensive Duelist'>Defensive Duelist</option>
    <option value='Dragon Fear'>Dragon Fear</option>
    <option value='Dragon Hide'>Dragon Hide</option>
    <option value='Drow High Magic'>Drow High Magic</option>
    <option value='Dual Wielder'>Dual Wielder</option>
    <option value='Dungeon Delver'>Dungeon Delver</option>
    <option value='Durable'>Durable</option>
    <option value='Dwarven Fortitude'>Dwarven Fortitude</option>
    <option value='Eldritch Adept'>Eldritch Adept</option>
    <option value='Elemental Adept'>Elemental Adept</option>
    <option value='Elven Accuracy'>Elven Accuracy</option>
    <option value='Fade Away'>Fade Away</option>
    <option value='Fey Teleportation'>Fey Teleportation</option>
    <option value='Fey Touched'>Fey Touched</option>
    <option value='Fighting Initiate'>Fighting Initiate</option>
    <option value='Flames of Phlegethos'>Flames of Phlegethos</option>
    <option value='Grappler'>Grappler</option>
    <option value='Great Weapon Master'>Great Weapon Master</option>
    <option value='Gunner'>Gunner</option>
    <option value='Healer'>Healer</option>
    <option value='Heavily Armored'>Heavily Armored</option>
    <option value='Heavy Armor Master'>Heavy Armor Master</option>
    <option value='Infernal Constitution'>Infernal Constitution</option>
    <option value='Inspiring Leader'>Inspiring Leader</option>
    <option value='Keen Mind'>Keen Mind</option>
    <option value='Lightly Armored'>Lightly Armored</option>
    <option value='Linguist'>Linguist</option>
    <option value='Lucky'>Lucky</option>
    <option value='Mage Slayer'>Mage Slayer</option>
    <option value='Magic Initiate'>Magic Initiate</option>
    <option value='Martial Adept'>Martial Adept</option>
    <option value='Medium Armor Master'>Medium Armor Master</option>
    <option value='Metamagic Adept'>Metamagic Adept</option>
    <option value='Mobile'>Mobile</option>
    <option value='Moderately Armored'>Moderately Armored</option>
    <option value='Mounted Combatant'>Mounted Combatant</option>
    <option value='Observant'>Observant</option>
    <option value='Orcish Fury'>Orcish Fury</option>
    <option value='Piercer'>Piercer</option>
    <option value='Poisoner'>Poisoner</option>
    <option value='Polearm Master'>Polearm Master</option>
    <option value='Prodigy'>Prodigy</option>
    <option value='Resilient'>Resilient</option>
    <option value='Revenant Blade'>Revenant Blade</option>
    <option value='Ritual Caster'>Ritual Caster</option>
    <option value='Savage Attacker'>Savage Attacker</option>
    <option value='Second Chance'>Second Chance</option>
    <option value='Sentinel'>Sentinel</option>
    <option value='Shadow Touched'>Shadow Touched</option>
    <option value='Sharpshooter'>Sharpshooter</option>
    <option value='Shield Master'>Shield Master</option>
    <option value='Skill Expert'>Skill Expert</option>
    <option value='Skilled'>Skilled</option>
    <option value='Skulker'>Skulker</option>
    <option value='Slasher'>Slasher</option>
    <option value='Spell Sniper'>Spell Sniper</option>
    <option value='Squat Nimbleness'>Squat Nimbleness</option>
    <option value='Svirfneblin Magic'>Svirfneblin Magic</option>
    <option value='Tavern Brawler'>Tavern Brawler</option>
    <option value='Telekinetic'>Telekinetic</option>
    <option value='Telephatic'>Telephatic</option>
    <option value='Tough'>Tough</option>
    <option value='War Caster'>War Caster</option>
    <option value='Wood Elf Magic'>Wood Elf Magic</option>
    "    
?>